name: padh_ai
description: "A new Flutter project for Padh AI."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.3.4
  flutter_tts: ^3.8.5
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # यहाँ से एसेट्स हटा दिए गए हैं ताकि Error न आए
